"""init translations table

Revision ID: 11065b6dc19f
Revises: 
Create Date: 2026-06-07 21:00:59.857539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11065b6dc19f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('source_lang', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('target_lang', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    # ### end Alembic commands ###
