"""add status field to translations

Revision ID: 93d4226949a7
Revises: 11065b6dc19f
Create Date: 2026-06-09 17:26:59.241402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d4226949a7'
down_revision: Union[str, Sequence[str], None] = '11065b6dc19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite 不支持直接加 NOT NULL 列，必须先加可空 + 填默认值，再设为 NOT NULL
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('status', sa.String(length=20), nullable=True, server_default='success')
        )
    # 已有数据用 server_default 已经填了 'success'，现在把它设为 NOT NULL
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False, server_default='success')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
